
field.formatter.settings.fallback:
  type: mapping
  label: 'Fallback formatter settings'
  mapping:
    formatters:
      type: sequence
      label: 'Formatters'
      sequence:
        - type: mapping
          label: 'Formatter settings'
          mapping:
            status:
              type: boolean
              label: 'Status'
            weight:
              type: integer
              label: 'Weight'
            settings:
              type: sequence
              label: 'Settings'
              sequence:
                - type: field.formatter.settings.[%key]
